### PR TITLE
[DNM] Add a way to compile asset chunks into one

### PR DESCRIPTION
**Pull request by DavisRayM**
Modifies the `build` command running the `build-non-split` script of which generate only 1 js and css file

### CODE REVIEW

**Comment by moshthepitt** [comment]
@DavisRayM do you still want to go with this approach?

**Comment by DavisRayM** [comment]
@moshthepitt no not any more, I think going with the chunks would be a better approach.

**Comment by moshthepitt** [comment]
Cool, should we close this PR?

**Comment by DavisRayM** [comment]
Yes

**Comment by DavisRayM** [comment]
Closing this PR for now, this doesn't seem like a route we'd like to go for right now.

**Pull request closed without merging**
